[build]
  # No build command is required for a purely static site
  command = ""
  # The directory to publish is the root directory
  publish = "."

[[headers]]
  for = "/frames/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
